---
title: "Automation Reliability in ATC: Mixed Model Analyses"
author: "ljgs"
date: "20/09/2021"
output:
  word_document:
    reference_docx: ../assets/apa.docx
  pdf_document: default
  html_document: default
---
by Luke Strickland

```{r load_packages_and_data, echo= FALSE , results = "hide", message=FALSE, warning=FALSE}



library(tidyverse)
library(ggplot2)
library(lme4)
library(car)
library(apa)
# library(lsmeans)
library(pander)
options(digits=2)
source("R/0-analysis_functions.R")

load("img/cleandats.RData")

cleandats <- cleandats %>% mutate(C = toupper(S)==R)

colnames(cleandats)[colnames(cleandats)=="sess"] <- "Session"
colnames(cleandats)[colnames(cleandats)=="cond"] <- "Condition"
colnames(cleandats)[colnames(cleandats)=="S"] <- "Stimulus"
colnames(cleandats)[colnames(cleandats)=="failtrial"] <- "Automation"

cleandats$Session <- factor(cleandats$Session, levels=c("1", "2", "3"),
                      labels=c("One", "Two", "Three"))

cleandats$Condition <- factor(cleandats$Condition , levels=c("AUTO_L", "AUTO_H", "MANUAL"),
                      labels=c("Automation_Low", "Automation_High", "Manual"))

cleandats$Automation <- factor(cleandats$Automation, levels=c("nonf", "fail"),
                      labels=c("Automation Success", "Automation Failure"))

cleandats$Stimulus <- factor(cleandats$Stimulus, levels=c("c", "n"),
                      labels=c("Conflict", "Non-conflict"))


tmp <- 1:24
tmp <- tmp[!tmp==4]
full_balance <- c(tmp, 28) 

cleandats <- cleandats %>% filter(s %in% full_balance)

theme_set(theme_simple())

accs <-
  cleandats %>% group_by(s, Stimulus, Condition, Automation, Session) %>% 
  filter(!is.na(R)) %>% summarise(acc = mean(C)) %>%
  arrange(s) %>% arrange(Automation)

RTs <- cleandats %>% group_by(s, Stimulus, Condition, Automation, Session) %>% 
  filter(C) %>% 
  summarise(RT=mean(RT))%>% arrange(Automation)


```



```{r, echo= FALSE, include=FALSE}
library(ltm)

Auto_Trust_Scores <- read_csv("Auto_Trust_Scores.csv")

Auto_Trust_Long <- Auto_Trust_Scores %>%  pivot_longer(cols=starts_with("D"), 
               names_to = c("Session", "Condition", "Q"),
               names_pattern=
                 "D(.)_(.)_Q(.)")



trust_scores_p <- Auto_Trust_Long %>% group_by(Participant, Session, Condition) %>% 
  summarise(score=mean(value, na.rm=T))

names(trust_scores_p)[1] <- "s"

trust_cond <- trust_scores_p %>% group_by(Condition) %>% summarise(mean(score))
trust_cond_SE <- se2(trust_scores_p, facs="Condition", dvnam="score")

cronbach_d1_H <- cronbach.alpha((Auto_Trust_Scores %>% filter(Participant %in% full_balance) %>% filter(!Participant %in% c("13")) %>% dplyr::select(-Participant) %>% dplyr::select(starts_with("D1_H"))))

cronbach_d2_H <- cronbach.alpha((Auto_Trust_Scores %>% filter(Participant %in% full_balance) %>% dplyr::select(-Participant) %>% dplyr::select(starts_with("D2_H"))))

cronbach_d3_H <- cronbach.alpha((Auto_Trust_Scores %>% filter(Participant %in% full_balance) %>% dplyr::select(-Participant) %>% dplyr::select(starts_with("D3_H"))))


cronbach_d1_L <- cronbach.alpha((Auto_Trust_Scores %>% filter(Participant %in% full_balance) %>% filter(!Participant %in% c("2")) %>% dplyr::select(-Participant) %>% dplyr::select(starts_with("D1_L"))))

cronbach_d2_L <- cronbach.alpha((Auto_Trust_Scores %>% filter(Participant %in% full_balance) %>% dplyr::select(-Participant) %>% dplyr::select(starts_with("D2_L"))))

cronbach_d3_L <- cronbach.alpha((Auto_Trust_Scores %>% filter(Participant %in% full_balance) %>% dplyr::select(-Participant) %>% dplyr::select(starts_with("D3_L"))))


alpha_df <- 
  as.data.frame(list("High Reliability" = c(cronbach_d1_H$alpha, cronbach_d2_H$alpha,cronbach_d3_H$alpha),
  "Low Reliability"= c(cronbach_d1_L$alpha, cronbach_d2_L$alpha,cronbach_d3_L$alpha)))

rownames(alpha_df) <- c("Session One", "Session Two", "Session Three")


pandoc.table(round(alpha_df,2))


pandoc.table(
  trust_scores_p %>% group_by(Condition) %>% summarise(cor(score[Session=="1"],
                                                         score[Session=="2"]))
)

pandoc.table(
  trust_scores_p %>% group_by(Condition) %>% summarise(cor(score[Session=="1"],
                                                         score[Session=="3"]))
)

pandoc.table(
  trust_scores_p %>% group_by(Condition) %>% summarise(cor(score[Session=="2"],
                                                         score[Session=="3"]))
)





pandoc.table(
  trust_scores_p %>% group_by(Condition) %>% summarise(cor(score[Session=="1"],
                                                         score[Session=="2"]))
)

pandoc.table(
  trust_scores_p %>% group_by(Condition) %>% summarise(cor(score[Session=="2"],
                                                         score[Session=="3"]))
)



```
